version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'bottle'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./SQL/bottle.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      bottle_network:
        ipv4_address: 172.20.0.10

  bottle:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: bottle
    environment:
      PORT: 8080
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      - db
    networks:
      bottle_network:
        ipv4_address: 172.20.0.20

# Names our volume
volumes:
  my-db:

networks:
  bottle_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16