version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'bottle'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./SQL/bottle.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      bottle_network:
        ipv4_address: 172.20.0.10

  bottle:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: bottle
    environment:
      PORT: 8080
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      - db
    networks:
      bottle_network:
        ipv4_address: 172.20.0.20

  cache:
    image: redis:6.2-alpine
    restart: always
    container_name: cache
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${PASS}
    volumes:
      - cache:/data
    networks:
      bottle_network:
        ipv4_address: 172.20.0.30

volumes:
  my-db:
  cache:

networks:
  bottle_network:
    external: false
    name: bottle
    ipam:
      config:
        - subnet: 172.20.0.0/16